name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Droplet
      run: |
        scp -o StrictHostKeyChecking=no -r . root@${{ secrets.DROPLET_IP }}:/root/expense-tracker

    - name: SSH & Deploy
      run: |
        ssh root@${{ secrets.DROPLET_IP }} <<EOF
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        export JWT_SECRET=${{ secrets.JWT_SECRET }}
        export JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }}
        cd /root/expense-tracker
        docker-compose up --build -d
        EOF
