name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH environment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

    - name: Copy files to Droplet
      run: |
        scp -r . root@${{ secrets.DROPLET_IP }}:/root/expense-tracker

    - name: SSH & Deploy
      run: |
        ssh root@${{ secrets.DROPLET_IP }} 'cd /root/expense-tracker && docker-compose up --build -d'
